### ISSUE TITLE
Installing it on windows

### ISSUE THREAD

**Issue by wagenrace** [Labelbox/labelbox-python#10]
Just so other people can be saved the hell I went to:
If you do 'pip install labelbox' and you don't have rasterio install you get an error "ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable."

This can be solved very simply by installing rasterio via anaconda and all your troubles are gone (except labeling itself, you still have to do that :P )

details:
- Windows 10 Home
- Python 3.6
- Anaconda 3.7

**Comment by feynmanliang** [comment]
Thanks for reporting and solving! I will look into fixing the rasterio dependency, but in the meantime your workaround as well as using WSL are both fine solutions!

**Comment by Kenc44** [comment]
Well not sure will it be helpful after this, but I was facing some errors running `pip install labelbox` but got it resolved by MANUALLY downloading GDAL, rasterio and Shapely wheels and installing them before running `pip install labelbox` again and everything works fine. The wheels can be downloaded from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/)

**Comment by HabibuMukhandi** [comment]
Those GDAL, shaperly and rasterio wheels are only support with python 2.7 and win 32 bit OS. Nothing for win 64 bit Intel

**Comment by Kenc44** [comment]
> 
> 
> Those GDAL, shaperly and rasterio wheels are only support with python 2.7 and win 32 bit OS. Nothing for win 64 bit Intel

My system is running on Win 10 64-bit , Python 3.7 if it helps.

**Comment by HabibuMukhandi** [comment]
@Kenc44  did you use Anaconda while installing or plain pip?

**Comment by Kenc44** [comment]
@HabibuMukhandi Im using plain pip

**Comment by HabibuMukhandi** [comment]
![pip](https://user-images.githubusercontent.com/52918932/61524620-154f5080-aa17-11e9-9c41-9b75edf4f63f.png)

**Comment by HabibuMukhandi** [comment]
That is the download page for those packages!!

**Comment by Aarekaz** [comment]
This issue is still happening to me. I even downloaded the whl for rasterio and gdal but its not installing.
![image](https://user-images.githubusercontent.com/36888347/155182608-defcc8a5-d270-4fed-909b-c61097314a3f.png)

gdal gets installed, but when I try to install rasterio it throws this error:
