### ISSUE TITLE
Is embedding not a reserved field anymore?

### ISSUE THREAD

**Issue by praneethys** [Labelbox/labelbox-python#1041]
I see that embedding is a reserved field as show in this [example](https://github.com/Labelbox/labelbox-python/blob/develop/examples/basics/data_row_metadata.ipynb) and also [this tutorial](https://docs.labelbox.com/reference/import-a-labeled-dataset-text-1). However, I only see tag, split and captureDateTime as reserved fields. 

<img width="717" alt="Screenshot 2023-03-31 at 5 27 31 PM" src="https://user-images.githubusercontent.com/61710414/229234757-ca177541-02b4-47d8-b852-b30feafa0904.png">

Please update the tutorial and examples if things have changed. Otherwise, let me know what I'm missing here.

Error:
```
embedding_field = metadata_ontology.reserved_by_name["embedding"]
KeyError: 'embedding'
```

**Comment by manuaero** [comment]
this is the new way of importing embeddings: https://docs.labelbox.com/reference/custom-embeddings#step-3-create-a-custom-embedding-type. We are in process of releasing Python SDK support (2-3 weeks ETA)
