### ISSUE TITLE
where=(Dataset.deleted==True) didn't seem to work

### ISSUE THREAD

**Issue by haodang** [Labelbox/labelbox-python#1082]
When getting deleted/undeleted datasets, I used [get_datasets](https://github.com/Labelbox/labelbox-python/blob/5c50da5385f0a37abc1abfd3d470678a3ef89796/labelbox/client.py#L507) as follows
```
datasets = client.get_datasets(where=(Dataset.deleted == True))
```

However, it doesn't seem to make a difference whether I pass `False` or `True`, `next(datasets)` always gave me the same dataset.

labelbox: 3.45.0

**Comment by manuaero** [comment]
We don't allow recovering deleted datasets. This field might have been overlooked and exposed in public APIs

**Comment by haodang** [comment]
Thanks, that's good to know!

If recovering is not allowed, can the API avoid returning deleted datasets? In my case, I'm still getting deleted datasets.

**Comment by paultancre** [comment]
`get_datasets` shouldn't return deleted dataset at all if it does please contact support providing the dataset id so we can investigate.
Contact support : https://docs.labelbox.com/docs/contacting-customer-support
