### ISSUE TITLE
How to get "existing" Global_keys ?

### ISSUE THREAD

**Issue by FrsECM** [Labelbox/labelbox-python#1117]
Hello,
With the global key system it's impossible to upload an image with the same global key.
In my case, we would like to use it to guaranty the unicity of our datarows in labelbox.

We have cron jobs that will upload datarows every days, but we have overlaps and we would like to use a well choosen global key in order to check if the datarows already exists or not.

To do that, i would like to use this method but with global keys that don't necessary exists :

```python
datarow_uids = client.get_data_row_ids_for_global_keys(global_keys)
for i, key in enumerate(global_keys):
     if datarow_uids ["results"][i] != "":
        our_datarow[key].uid = datarow_uids["results"][i]
# Later
if our_datarow[key].uid is not None:
     # Do not upload
```

The problem is that when we call ***get_data_row_ids_for_global_keys*** with unexisting global keys, it is very slow and generates a lot of warnings like that : 
```bash
WARNING:labelbox.client:There are errors present. Please look at 'errors' in the returned dict for more details
WARNING:labelbox.client:There are errors present. Please look at 'errors' in the returned dict for more details
WARNING:labelbox.client:There are errors present. Please look at 'errors' in the returned dict for more details
WARNING:labelbox.client:There are errors present. Please look at 'errors' in the returned dict for more details
WARNING:labelbox.client:There are errors present. Please look at 'errors' in the returned dict for more details
WARNING:labelbox.client:There are errors present. Please look at 'errors' in the returned dict for more details
````

Would it be possible to change the behavior to just return a list with the same size of the provided one, containing empty strings where the global_key do not exists and the uid when it exists ?

Let’s imagine we have a list like that : 

```python
global_keys = ['key_1','key_2','already_existing_3','key4',...,'already_existing_5']
res = client.get_data_row_ids_for_global_keys(global_keys)
print(res)
# ---
# WARNING:labelbox.client:There are errors present. Please look at 'errors' in the returned dict for more details
# {'status': 'PARTIAL SUCCESS', 'results': ['cl84zszs302z7074c8u7m2osx', 'cl84zszs302yz074ccg1acwu5', 'cl84zszs302z3074c6aahhq3q'], 'errors': [{'global_key': '<a non-existent key>', 'error': 'Data Row not found'}]}
```

**How do i know who is who in results ?**

I think it would be better to :

- Not send the warning
- Send a status 'PARTIAL SUCCESS' anyway
- create a results list, the same size than global_keys

I can't use ***get_data_row_ids_for_global_keys*** like it is for the moment because of that behaviour !
![image](https://github.com/Labelbox/labelbox-python/assets/26071804/e395aa90-b201-41fc-ae71-b04ceac56ac1)

Thanks,
Regards,

**Comment by Gabefire** [comment]
Hey,
This behavior looks like it was approved. I tested this with over 100,000 nonexistent data row IDs. It took  5 seconds to resolve and will time out if you go over a certain limit (1 mil+) which is to be expected. An easy way around your problem is to run a script like this at the create data row level :
```python
task = dataset.create_data_row()

if task.errors:
    for error in task.errors:
        if 'Duplicate global key' in error['message'] and dataset.row_count == 0:
            # Do something if global key already exists 
``` 
Thanks
Gabe
