### ISSUE TITLE
Change `opencv-python` to `opencv-python-headless` in `requirements.txt`

### ISSUE THREAD

**Issue by vladyml** [Labelbox/labelbox-python#1175]
Usage of `opencv-python` as dependency in `requirements.txt` puts a significant constraint for using labelbox together with opencv in environments without graphical capabilities. 

For instance, installing labelbox as it is now on server machine would break simple `import cv2` if additional libs for graphic environment are not installed (think opengl and similar). 

Hence, if possible, it would be great to have that dependency changed to `opencv-python-headless`, which offers a more lightweight setup.

**Comment by Gabefire** [comment]
Hi @vladyml 
I appreciate the feedback and working to get this adjusted.

Thanks,
Gabe
