### ISSUE TITLE
Python 3.10 / 3.11 official support

### ISSUE THREAD

**Issue by SimonSchick** [Labelbox/labelbox-python#1261]
According to https://github.com/Labelbox/labelbox-python/releases/tag/v.3.53.0 3.10 is officially supported, but your `README` doesn't reflect that, you might want to update.

Further I'd like to enquire if this package is generally compatible with python 3.11 or not.

**Comment by adam-homeboost** [comment]
Same question for python 3.12

**Comment by paultancre** [comment]
We will update README, appreciate the feedback @SimonSchick.
For clarity requirements will stipulate the following versions : 3.7, 3.8, 3.9 and 3.10
