### ISSUE TITLE
Missing V1 fields from V2 project export

### ISSUE THREAD

**Issue by ShantanuKumar** [Labelbox/labelbox-python#1415]
Hi, earlier in V1 there were fields which are unavailable in V2 when we export the annotations using python SDK (=3.61.2). 
For example these two fields. Internally during V1 export, we filter out annotations which have open issues and/or were benchmark images.
```
"Benchmark Agreement": -1,
"Has Open Issues": 1,
```

I have seen that currently when we use V2 export these annotations which we had ignored earlier are getting synced. I want to exclude them. Is there a substitute for it in V2? The only filtering criteria which seems relevant is `workflow_status="Done"`. We already use that.

**Comment by Gabefire** [comment]
Hey! We currently don't have a way to filter out annotations with issues with export_v2. I know we are actively working to provide improvements to our issues and comments feature. I will put this in as a feature request.
