### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by awsaf49** [Labelbox/labelbox-python#148]
I can't download the masks from the `InstanceURL` I've tried using `wget` or `requests` but nothing seems to work. When I try to access the link using browser I get this message, 
```An authentication token is required to complete this operation. The Authorization header must contain your API key.```
I tried this approach to include **labelbox API**,
```
headers = {'Authorization': f"{labelbox}"}
response = requests.get(link, headers=headers)
```
but it's not working I'm getting this as output `<Response [401]>`. 
I think it's due to the latest update.

**Comment by msokoloff1** [comment]
We are fixing this right now. I'll update you here when it is resolved.

**Comment by awsaf49** [comment]
@msokoloff1 thanks for your response, eagrly waiting for it.

**Comment by msokoloff1** [comment]
@awsaf49 Its back. Sorry about that!
