### ISSUE TITLE
GraphQL Injection

### ISSUE THREAD

**Issue by aydinnyunus** [Labelbox/labelbox-python#1548]
Hi Team,
I found GraphQL Injection vulnerability on labelbox.
GraphQL Injection (also known as GQL Injection) is a security vulnerability that occurs when an attacker is able to manipulate GraphQL queries to perform unauthorized actions or gain access to sensitive data. It is similar to SQL injection but specific to GraphQL queries.
• https://github.com/Labelbox/labelbox-python/blob/develop/labelbox/schema/organization.py#L112
• https://github.com/Labelbox/labelbox-python/blob/develop/labelbox/schema/organization.py#L129
• https://github.com/Labelbox/labelbox-python/blob/develop/labelbox/schema/organization.py#L179
Remediation
Use parameterized queries or prepared statements to separate user inputs from the query structure. This helps prevent attackers from injecting malicious code into the query.

**Comment by Gabefire** [comment]
Hey,
Thank you for mentioning this! We are looking into this now!

**Comment by adrian-chang** [comment]
Hey there,

Appreciate the concern. We're reviewing this right now and we'll get back to you as soon as we can.

Thank you

**Comment by Gabefire** [comment]
Hey,
So, we got this reviewed and are working internally on a solution. We do appreciate your mentioning and will investigate further. For now, we will close this issue. 

Thanks,
Gabe
