### ISSUE TITLE
`uiMode` property

### ISSUE THREAD

**Issue by rafaelpadilla** [Labelbox/labelbox-python#1674]
I couldn't read/change the property `uiMode` from the python API.
Is there a way to modify it or only via browser?

**Comment by Gabefire** [comment]
Hey Rafael,
This is currently something that is not available inside our SDK. But I'm taking a peak to see how difficult adding would be.

Thanks,
Gabe

**Comment by Gabefire** [comment]
This feature will be added in the next release. You will be able to create ontologies and modify existing ontologies by using this field inside your classification:
```python
ui_mode=lb.Classification.UIMode.HOTKEY
```
Thank you for your request!

**Comment by rafaelpadilla** [comment]
Great! Thank you @Gabefire :rocket:
