### ISSUE TITLE
connect_ontology(ontology) does not exist

### ISSUE THREAD

**Issue by rafaelpadilla** [Labelbox/labelbox-python#1743]
The official documentation [here](https://docs.labelbox.com/reference/ontology#connect-an-ontology-to-a-project) affirms that the function `connect_ontology` can be used to set an ontology to an existing project.

However, the function `connect_ontology` does not exist.

LabelBox lib version '3.74.0'

**Comment by Gabefire** [comment]
Hey Rafael! We had a recent removal of a feature ([custom editors](https://docs.labelbox.com/docs/deprecations#custom-editor)) and with that removal we deprecated the `setup_editor `method that was associated with connecting ontologies and custom editors prior to 3.75. The latest SDK version 3.75 added `connect_ontology` in place of `setup_editor`to be more consistent and represent what the method does. If you used `setup_editor` it would accomplish the same thing for that version.

**Comment by Gabefire** [comment]
Hey @rafaelpadilla! I believe you commented back but we are working on giving backwards support to projects without ontologies.

**Comment by Gabefire** [comment]
Hi @rafaelpadilla Im going to resolve this issue since it has been some time we are doing actions to maintain backwards compat but for this particular case this ontology feature is intended
