### ISSUE TITLE
Not able to create datarows apparant size limit reached

### ISSUE THREAD

**Issue by jang-vapar** [Labelbox/labelbox-python#1776]
# Describe the bug
When trying to upload 150 datarows with the SDK I get following error message: "Failed to access URL: 404:The specified resource does not exist."
When uploading 100 datarows the task succeeds without errors. 
It seems there is a limit to the amount of rows that can be sent, but it's not specified anywhere in the documentation and neither is the error message relevant to the issue.

# To reproduce
1. Use method 'upsert_data_rows' or 'create_datarows'
2. Pass parameters 'datarows' list with 150 or more items
3. See error "Failed to access URL: 404:The specified resource does not exist."

# Expected behavior
Change the error specifying that the batch size limit has been exceeded and add that limit to the documentation.

# Screenshots / Videos
If applicable, add screenshots or videos to help explain your problem.

# Environment (please complete the following information
 - OS: Azure Databricks
 - Python Version: 3.10.12
 - SDK + SDK Version: labelbox@3.75.0 / labelbox@3.77.0
 - Python Environment [requirements.txt](https://github.com/user-attachments/files/16720580/requirements.txt))]

**Comment by Gabefire** [comment]
Hi @jang-vapar ,
Have you updated to the latest version? I tried to reproduce this issue with no luck.

**Comment by Gabefire** [comment]
Hi,
I tested this locally and could not reproduce
