### ISSUE TITLE
SSLError since version 3.76 - VPN and self signed certificates

### ISSUE THREAD

**Issue by FrsECM** [Labelbox/labelbox-python#1794]
# Describe the bug
In my company we use a VPN and we have a certificate chain with custom certificates.
In order to make it work with labelbox, we have do declare our custom certificates to an environment variable : 

```bash
(labelbox) ➜   echo $SSL_CERT_FILE
/etc/ssl/certs/ca-certificates.crt
```

Before v3.76 of the SDK (to version 3.75.1), this simple code was working :
```python
import labelbox
client = labelbox.Client(api_key="APIKEY")
projects = client.get_projects()
print(next(projects))
print('terminé')
```
```bash
<Project {
    "auto_audit_number_of_labels": 1,
    "auto_audit_percentage": 1,
    "created_at": "2024-07-09 08:50:49+00:00",
    "data_row_count": 0,
    "description": "",
    "editor_task_type": "EditorTaskType.Missing",
    "last_activity_time": "2024-09-04 13:24:21+00:00",
    "media_type": "MediaType.Image",
    "model_setup_complete": null,
    "name": "Project Name",
    "queue_mode": "BATCH",
    "setup_complete": null,
    "uid": "labelbox uid",
    "updated_at": "2024-09-04 13:24:21+00:00",
    "upload_type": "UploadType.Manual"
}>
```

After v3.76 of the SDK, now it returns a SSL Error : 
```bash
Unknown error: HTTPSConnectionPool(host='api.labelbox.com', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)')))
```

# To reproduce
1. Use SDK 'v3.76.0'
2. Call Labelbox
3. See error

# Expected behavior
It should be working exactly the same way than in version 3.75.1

# Screenshots / Videos
If applicable, add screenshots or videos to help explain your problem.
![image](https://github.com/user-attachments/assets/4386a61d-7705-4ff4-8847-b117865c474f)

![image](https://github.com/user-attachments/assets/a9acbf63-b70b-4bbc-a95a-492d49190622)

# Environment (please complete the following information
 - OS: WSL Ubuntu 22.04
 - Python Version: [e.g. 3.10]

**Comment by FrsECM** [comment]
Got the fix, we just have to switch to another env variable with certificates

export REQUESTS_CA_BUNDLE='/etc/ssl/certs/ca-certificates.crt'

Issue can be close for me.

**Comment by paultancre** [comment]
For posterity : 
Issue fixed with this command
`export REQUESTS_CA_BUNDLE='/etc/ssl/certs/ca-certificates.crt'`
shared by the requestor on a support ticket, closing this as resolved.

**Comment by FrsECM** [comment]
@paultancre, it seems not to be enough to fix the issue on my environment

> For posterity : Issue fixed with this command `export REQUESTS_CA_BUNDLE='/etc/ssl/certs/ca-certificates.crt'` shared by the requestor on a support ticket, closing this as resolved.

Can you re-open the ticket ?
![image](https://github.com/user-attachments/assets/02495a9c-1dab-4d7b-89d8-a928977bf04e)


A fix that work : 
```bash
pip install pip-system-certs
```

**Comment by paultancre** [comment]
I was about to ask to run : 
`openssl s_client -show certs -connect api.labelbox.com:443` a man in the middle or proxy can interfere with other dependencies.
Thank you for suggesting https://pypi.org/project/pip-system-certs/

**Comment by paultancre** [comment]
created community article: https://community.labelbox.com/t/how-to-fix-sslcertverificationerror-1-ssl-certificate-verify-failed-certificate-verify-failed-self-signed-certificate-in-certificate-chain/1476
