### ISSUE TITLE
6.0 release breaks client exception imports

### ISSUE THREAD

**Issue by adam-homeboost** [Labelbox/labelbox-python#1886]
# Describe the bug

Client exception classes no longer available in module exports.

# To reproduce

Prior to 6.0 you could write:

```
    import labelbox

    client = labelbox.Client(...)
    try:
        client.do_something()
    except labelbox.exceptions.SomeException:
        ...
```

This now breaks as labelbox no longer exports exceptions and they are now located on lbox.exceptions.  "lbox?".

Note also that "lbox" has zero typing and fails mypy, therefore changing the import fails mypy checking too.

Please provide a compatibility shim so that existing code does not break or at least some kind of deprecation warning and documentation changes.

# Expected behavior
This code should not break all of a sudden with zero warning.  At least deprecate it for a bit.

Expect types for "lbox" module.

 - OS: linux
 - Python Version: 3.8.12
 - SDK + SDK Version: 6.0

**Comment by vbrodsky** [comment]
Hello @adam-homeboost 
For sdk v.6.0.0 we have moved exceptions along with some other classes dealing with api to a separate module `lbox`. This try this change

```
import lbox


client = labelbox.Client(...)
try:
    client.do_something()
  except lbox.exceptions.SomeException:
        ...
```
