### ISSUE TITLE
project.export_labels() returns google cloud link

### ISSUE THREAD

**Issue by bearpelican** [Labelbox/labelbox-python#23]
exports_labels() now returns something like: `gs://labelbox-exports/ck1jziw8x9apm0794mxlweb8e`

Is this expected? I believe this use to be a http download url (as of a few days ago).

**Comment by kyleowens10** [comment]
Hi @bearpelican, thank you for the report. We corrected the return value from our API for `downloadUrl` and now return a signed URL to download your label export.
