### ISSUE TITLE
Create data rows does not work when data is created from another process

### ISSUE THREAD

**Issue by michael-dyer-snapdocs** [Labelbox/labelbox-python#250]
Hi all, found a small inconsistency in the python API. We are creating a lot of data and was using a separate process to create the list to import into labelbox and got the error 

`labelbox.exceptions.InvalidQueryError: DataRow.row_data missing when creating DataRow.('DataRow.row_data missing when creating DataRow.', None)`
I believe this is because https://github.com/Labelbox/labelbox-python/blob/9170913829f0ec697e2bad6951bf3f7d1bf4c10b/labelbox/schema/dataset.py#L145 checks to see if the field objects have the same id, not to see if they are the same type, so creating in a different process would give it a different id and cause this error.
I have a minimal example to reproduce the error.
I solved the problem by creating the list in the same process, but thought I would just raise this here for your awareness
Thanks!

```
from labelbox import Client, DataRow
import concurrent.futures

import uuid

def get_items():
    items = [{
    DataRow.row_data: "https://picsum.photos/200/300",
    DataRow.external_id: str(uuid.uuid4())
    }]
    return items

def main():
    client = Client()
    dataset = client.create_dataset(name="test_dataset")
    items = get_items()

    task = dataset.create_data_rows(items) # no error
    task.wait_till_done()
    with concurrent.futures.ProcessPoolExecutor() as executor:
        future = executor.submit(get_items)
        items = future.result()
    dataset = client.create_dataset(name="test_dataset-2")
  
    
    task = dataset.create_data_rows(items) # error here
    task.wait_till_done()

if __name__ == '__main__':
    main()
```

**Comment by msokoloff1** [comment]
Thanks for collecting this code snippet and sharing! The problem is that when you create the process pool each process constructs a new copy of the Field class. So each DataRow.row_data here is actually not the same instance and therefore not equal and fails our comparison check.
```
def get_items():
    items = [{
    DataRow.row_data: "https://picsum.photos/200/300",
    DataRow.external_id: str(uuid.uuid4())
    }]
```

Here is a non-labelbox example of what is going on.
```
 import concurrent.futures
 
 class Field:
     ...
 
 class DataRow:
     field = Field()
 
 
 def getField():
     return DataRow.field
 
 
 if __name__ == '__main__':
     with concurrent.futures.ProcessPoolExecutor(max_workers =2 ) as executor:
         a = executor.submit(getField)
         b = executor.submit(getField)
         print(a.result() == b.result())
```

To get around this problem, you can set the field names with strings. 
```
{
    "row_data": "https://picsum.photos/200/300",
    "external_id": str(uuid.uuid4())
}
```
However, I agree that we should make the same data structure work whether or not you are using multiple processes. I'll play around with this when I get some free time.
