### ISSUE TITLE
Failed to upload annotation file. unauthorized to perform

### ISSUE THREAD

**Issue by minsu1206** [Labelbox/labelbox-python#333]
![image](https://user-images.githubusercontent.com/59243570/140710389-1399ace6-1c1e-4818-9917-a6f4770ce119.png)

Hi
I met error at "mal_with_subclasses.ipynb"
I just followed your codes and just replace variable 'API_KEY' with  my API key  (string type)
Except putting my API_KEY, No changes at all.

I made new api-key and tried again, but the result was same.
Please lt me know how to solve
Thank you.

**Comment by msokoloff1** [comment]
This is an authorization issue. Your organization is not allowed to use mal features. If you think that this is incorrect or want to get your permissions upgraded you can reach out to support. 

I don't think that this is an SDK bug so I am going to close this. If you feel like this is a bug feel free to reopen.
