### ISSUE TITLE
create_data_rows returns Task instance with no details on status

### ISSUE THREAD

**Issue by remidbs** [Labelbox/labelbox-python#351]
When uploading rows to a Dataset using `Dataset.create_data_rows`, I get an instance of `Task` class with name, status and completion_percentage, but when status is "FAILED", I have no more information on the error. It would be convenient to have more details on it.

**Environment**:  `labelbox==3.10.0` and `python 3.6`.

**Comment by msokoloff1** [comment]
That information isn't easily accessible from the client. Understanding why your task failed would have to be investigated by the engineering team. If you reach out to support they can get engineer to investigate for you. I'll discuss making the appropriate backend changes to expose this.

**Comment by msokoloff1** [comment]
I'm

**Comment by remidbs** [comment]
Hello and thank you for your answer. I use indeed text data and it could be that some contain emojis. Thank you for the workaround, I'll give it a try 👍
