### ISSUE TITLE
Inconistent "Authentication required" when downloading images by url

### ISSUE THREAD

**Issue by zimonitrome** [Labelbox/labelbox-python#362]
We have some sample code akin to:

```
import os
import requests
from labelbox import Client

labelboxApiKey = os.getenv('LABELBOX_API_KEY')
client = Client(labelboxApiKey)
project = client.get_project(args.projectid)
datasets = list(project.datasets())
for ds in datasets:
    data_rows = ds.export_data_rows()
    for dr in data_rows:
        url = dr.row_data
        response = requests.get(url=url, headers=client.headers)
```

The value of `response.content` has been inconsistent throughout the day. We expect it to contain a jpeg image, but some responses to this request returns:

`b"<?xml version='1.0' encoding='UTF-8'?><Error><Code>AuthenticationRequired</Code><Message>Authentication required.</Message></Error>"`

Is the API being updated? Is there some authentication token that needs to be passed on manually other than what is present in `client.headers`?

This code has worked fine for months and this problem seems to have appeared during the past 2 weeks.

**Comment by msokoloff1** [comment]
This is auth issue is coming from gcs. We are currently investigating this but as a quick workaround you can add the following headers to your request.
```
headers =  {
    "cache-control": "max-age=0",
}
```
I am going to close this because it is not an SDK issue and there is a workaround.
