### ISSUE TITLE
Issues with v3.13

### ISSUE THREAD

**Issue by venuv** [Labelbox/labelbox-python#427]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-e6849dd84512> in <module>()
     11 
     12 #ml
---> 13 from labelbox import Client
     14 import torch
     15 import torch.utils.data

5 frames
/usr/local/lib/python3.7/dist-packages/labelbox/data/annotation_types/geometry/line.py in <module>()
      1 from typing import List, Optional, Union, Tuple
      2 
----> 3 import geojson
      4 import numpy as np
      5 import cv2

ModuleNotFoundError: No module named 'geojson'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by msokoloff1** [comment]
We are releasing a fix now. Sorry about this.

**Comment by msokoloff1** [comment]
fixed in the last patch
