### ISSUE TITLE
MAL Demo Authorization Error 

### ISSUE THREAD

**Issue by 4ri4Slr** [Labelbox/labelbox-python#429]
I am trying to use the model-assisted-labeling feature. However, when I run the demo mal_using_annotation_types.ipynb, I get the following error:

AuthorizationError                        Traceback (most recent call last)

[<ipython-input-31-990fe41ad9e1>](https://localhost:8080/#) in <module>()
      1 upload_task = project.upload_annotations(name=f"upload-job-{uuid.uuid4()}",
      2                                          annotations=ndjsons,
----> 3                                          validate=True)
      4 # Wait for upload to finish
      5 upload_task.wait_until_done()

5 frames

[/usr/local/lib/python3.7/dist-packages/labelbox/client.py](https://localhost:8080/#) in execute(self, query, params, data, files, timeout, experimental)
    214         if authorization_error is not None:
    215             raise labelbox.exceptions.AuthorizationError(
--> 216                 authorization_error["message"])
    217 
    218         validation_error = check_errors(["GRAPHQL_VALIDATION_FAILED"],

AuthorizationError: You are unauthorized to perform this action('You are unauthorized to perform this action', None)

Is this because I am trying to access a paid feature?

**Comment by msokoloff1** [comment]
I updated the permissions. You should be able to use this feature now. Feel free to re-open the issue if you are still having a problem.
