### ISSUE TITLE
Extra logging info after upgrade to 3.14.0

### ISSUE THREAD

**Issue by DouglasLivingstone** [Labelbox/labelbox-python#468]
After upgrading from Labelbox 3.11 to 3.14, I'm seeing extra INFO logging by default, when I'd expect the logger to stay on the default WARNING level.

I've had a quick look, and my best guess is that the default logging level was changed to INFO in this commit which was included in 3.12: https://github.com/Labelbox/labelbox-python/commit/f85bc0d620955f2c38040dc16d425ba4b7863854

```
+ logging.basicConfig(level=logging.INFO)
```

Could you take this out please so that the default logging level is preserved? Happy to submit a PR!

**Comment by msokoloff1** [comment]
Thanks for bringing this to our attention. We can remove this in the next release.

**Comment by msokoloff1** [comment]
This was fixed in 3.16.0. Let me know if you are still having any related issues.
