### ISSUE TITLE
Loosen version requirements for requests?

### ISSUE THREAD

**Issue by kbrose** [Labelbox/labelbox-python#50]
Hello,

Is it possible to loosen the restrictions on the version for the `requests` library? Currently it's hard coded to [2.22.0](https://github.com/Labelbox/labelbox-python/blob/develop/setup.py#L16).

This makes it impossible to use the labelbox python SDK in an environment that also requires other versions of `requests`.

Perhaps it could go back to `>= 2.22.0` like it was before https://github.com/Labelbox/labelbox-python/pull/27?

**Comment by rllin** [comment]
this is handled in https://github.com/Labelbox/labelbox-python/releases/tag/v2.4.5 :)

**Comment by kbrose** [comment]
Thank you for your help!
