### ISSUE TITLE
In some cases response["data"] does not exist when called in the .execute() method

### ISSUE THREAD

**Issue by tomlockwood** [Labelbox/labelbox-python#53]
I have a free tier account that I was using for testing.  Some functions were disabled over the weekend, and when this happened, I was using the following code:
```python
from labelbox import Client

l = Client(api_key)

for p in l.get_projects():
    print(p)
```
and I got the response:

```
Traceback (most recent call last):
File "export.py", line 7, in <module>
for p in l.get_projects():
File ".venv/lib/python3.7/site-packages/labelbox/pagination.py", line 50, in __next__
results = self.client.execute(query, self.params)
File ".venv/lib/python3.7/site-packages/labelbox/client.py", line 172, in execute
return response["data"]
KeyError: 'data'
```
This error wasn't very informative, so in the case `response["data"]` does not exist, the SDK should return more verbose information about the request response?

Just calling `l.get_projects()` did not error.

Thanks heaps!

**Comment by tomlockwood** [comment]
Also thanks to support member Andy for helping me out with this issue!

**Comment by rllin** [comment]
thanks for the heads up @tomlockwood will make sure this gets on our roadmap for the sdk

**Comment by rllin** [comment]
handled in https://github.com/Labelbox/labelbox-python/releases/tag/v2.4.5 :)
