### ISSUE TITLE
Unknown Type "AttachmentType"

### ISSUE THREAD

**Issue by pfigliozzi** [Labelbox/labelbox-python#73]
I am getting an error when I try to run the `labelbox.schema.DataRow. create_metadata()` function. I get a `InvalidQueryError: Unknown type "AttachmentType".('Unknown type "AttachmentType".', None)`. I don't think "AttachmentType" is a valid type in your GraphQL database. The query that is attempted to run is:

https://github.com/Labelbox/labelbox-python/blob/42ba1747bf60cbe331a90948f7c054c54faa6e31/labelbox/schema/data_row.py#L52

I tried recreating the query in the GraphQL explorer and it puts a squiggle line under "AttachmentType" calling it an invalid type. I also don't see  "AttachmentType" when I search the documentation explorer for the GraphQL explorer.

**Comment by pfigliozzi** [comment]
I looked into it more, in line 52 linked above, it should be "MetadataType" and not "AttachmentType" according to the GraphQL  documentation. At least that is what worked for me.

**Comment by msokoloff1** [comment]
The backend was updated around the time you were having trouble. This should be resolved now. Please reopen the issue if you are still having problems.
