### ISSUE TITLE
Increase or manually specify retry time limit for raster fetching

### ISSUE THREAD

**Issue by zimonitrome** [Labelbox/labelbox-python#754]
https://github.com/Labelbox/labelbox-python/blob/2235baed2d0e76e25d272fed6a87252d3065c8b2/labelbox/data/annotation_types/data/raster.py#L119

We have quite a lot of data that may take hours to download. We have multiple times ran into 504 server timeouts and the 15 seconds of retrying is reached and thus the download is interrupted. Would it be possible to implement a manual duration for retrying by changing the above linked "15" seconds?

**Comment by paultancre** [comment]
Hello There, 
If this still ongoing please contact support : https://docs.labelbox.com/docs/contacting-customer-support.
Many thanks, 
Paul Tancré 
Labelbox Support
