### ISSUE TITLE
LabellingParameterOverrides is a dead end

### ISSUE THREAD

**Issue by vpipkt** [Labelbox/labelbox-python#76]
You can get a `LabellingParameterOverride` object from the `Project` method but it is not practically useful. The `uid` on this object is the identifier of the LabellingParameterOverride object itself which is fair enough. But there is no way to get the datarow relationship or the uid of that datarow.

So in practice it is not really useful because the API for setting overrides takes tuples of (`DataRow`, priority, numberOfLabels). If the   `LabellingParameterOverride`  has a relationship to its datarow you could write a program like this:

```
new_lpos = []

for lpo in proj.labeling_parameter_overrides():
    datarow = lpo.datarow() # function not defined
    new_lpos = (
        datarow,
        number_of_labels=lpo.number_of_labels + 1,
        priority=lpo.priority-10,
    )

proj. set_labeling_parameter_overrides(new_lpos)
```

Needless to say right now it is actually impossible to do something like this without going through the GraphQL API, or hacking away with a PaginatedCollection.

**Comment by msokoloff1** [comment]
Adding this now `datarow = lpo.datarow()`

**Comment by msokoloff1** [comment]
This has been merged to develop. If you need this functionality you can install from develop or wait until we release the next version (usually within a week).
