### ISSUE TITLE
MalformedQueryException: Cannot attach/detach dataset to/from a batch project

### ISSUE THREAD

**Issue by avi-quago** [Labelbox/labelbox-python#762]
hi, I am following your tutorials.
running on Databricks I'm getting this error when trying to connect a dataset (or a batch) to a project - 

`project.datasets.connect(dataset)`

same for 

`project.datasets.connect(batch)`

any advice / pointer will be appreciated.

**Comment by SamuelzXu** [comment]
I'm getting this error too

**Comment by paultancre** [comment]
Hello, a project can be either set for queue.Batch or queue.Dataset.
Your project is configured by default in `queue.Batch `from lib 
`from labelbox.schema.queue_mode import QueueMode` you cannot connect dataset to a batch project.
If you want to use dataset, you need to set your project to a dataset queue `queue.Dataset`(cannot be changed once project is set.)

**Comment by free-soellingeraj** [comment]
@paultancre 
When I try to configure my project with QueueMode.Dataset, I get:
```
QueueMode.Dataset will eventually be deprecated, and is no longer recommended for new projects. Prefer QueueMode.Batch instead.
Failed to create project: DataSet queue mode is deprecated. Please prefer Batch queue mode.
```

My end goal is to have a project that grows by adding more and more datasets.  How can I accomplish this?
