### ISSUE TITLE
Documentation questions on `Project.set_labeling_parameter_overrides`

### ISSUE THREAD

**Issue by vpipkt** [Labelbox/labelbox-python#77]
Several questions coming from Python SDK trying to work with labeleing parameter overrides.

1. Can the priority or number of labels member of the tuple be `None`? 
    1. I would assume that if one of these is `None` there will not be any change to the overrides?
    2. Documentation is unclear. It's also unclear if you can have a priority override without a number of labels override, and vice verse
1. What happens in edge cases such as:
    1. Override number of labels passed is less than the count of labels already created for a datarow
         - I would assume nothing would happen. But it is unclear what would happen.
    2. Changing the priority on a datarow that already has all the labels created (override 
    3. Does changing override number of labels cause a datarow to be re-queued if it already has labels created? Example: project consensus is 2, team members have created 2 labels for a certain datarow. Then the override number is set to 3. 
        - Will the datarow go back into the queue ?
        - If so will the new label task be assigned to a different team member than those that have already created labels?

**Comment by msokoloff1** [comment]
1. You must provide priority, number of labels, and data row. Priority and number of labels must be ints that are greater than 0.  None is invalid for any of the arguments.
2.
      1. Nothing happens. It won't delete the labels.
      2. The data row will not be re-enqueued if the priority changes after is has been labeled. 
      3. If the number of labels for that data row increase, the duplicates will be added to the queue.
                - Yes, the third copy will be added to the queue but not the others.
                - Also correct. This new copy will be assigned to another team member that did not label this same data row previously.
      

I updated the docstring a bit. Hopefully this is more helpful:
https://github.com/Labelbox/labelbox-python/blob/86221cb0b109dfdd83a61b9b5f610e7bf16085ca/labelbox/schema/project.py#L391-L426

This doesn't really address your questions but here is a tutorial that might be helpful for you or someone else on your team.
https://github.com/Labelbox/labelbox-python/blob/develop/examples/project_configuration/queue_management.ipynb
