### ISSUE TITLE
project.label_generator( ) doesn't finish nor tirgger timeout

### ISSUE THREAD

**Issue by mcloses** [Labelbox/labelbox-python#775]
As described on the title, exporting the labels through the API never finished nor triggers a timeout. At one point it even made my PC crash.

I had no problem downloading the labels through the export button on the platform and the size is not problematic (around 150 images with ~6000 instance masks).

Anyone has had this problem too? I've gone over the closed issues already but couldn't find anything either

**Comment by mcloses** [comment]
SOLVED: Need to initialize your Labelbox Client instance with named argument for API KEY:
`client = Client(api_key=API_KEY)`

I was instead using 
`client = Client(API_KEY)`
The client behaved like a normal one, but wouldn't retrieve the labels

**Comment by dvagala** [comment]
It's apparently a different cause, but I'm experiencing the same issue that the `project.label_generator( )`. It just hang, until the default 600sec timeout hit, and the script stops executing. 

My LabelBox project has only one annotated data row and is inside the `Done`.

I figured out though that if I provide `start` and `end` date it would work correctly.


```python
import labelbox

lb = labelbox.Client(api_key="some_api_key")
project = lb.get_project('some_project_id')

# Doesn't work - timeout
labels = project.label_generator()

# Does work
labels = project.label_generator(start="2023-03-07", end="2023-03-13")
```
