### ISSUE TITLE
Document Named Entities are not exported only the bounding boxes

### ISSUE THREAD

**Issue by jeromemassot** [Labelbox/labelbox-python#784]
Hi LabelBox team,

# Export labels created in the selected date range as a JSON file
labels = project.export_labels(download=True)

Applied to Document Named Entities labels, it does not export entities but only the bounding boxes.

I turned the "Save and export data" option on when I created the project.

The document seems to be deprecated.
There is no code example covering the export of labels when applied to Document type.

Thanks

Jerome

**Comment by paultancre** [comment]
Hello There,
If this is still ongoing please contact support : https://docs.labelbox.com/docs/contacting-customer-support.
Many thanks,
Paul Tancré
Labelbox Support
