### ISSUE TITLE
Why subtract from img_height?

### ISSUE THREAD

**Issue by tispratik** [Labelbox/labelbox-python#8]
https://github.com/Labelbox/labelbox-python/blob/f7ae35d383a0453eb2753cba8f012b67ad1f9ac6/labelbox/exporters/voc_exporter.py#L149

I wonder why we are subtracting from `img_height` for XY export function?

**Comment by feynmanliang** [comment]
Thanks; this was for backwards compatibility but will be removed in v1.0.0
