### ISSUE TITLE
Is there any way to create labels on the new frontend API?

### ISSUE THREAD

**Issue by bearpelican** [Labelbox/labelbox-python#88]
We are currently trying to update to new frontend API for our project. However, it looks like create_label only works for the legacy project. https://github.com/Labelbox/labelbox-python/blob/bc2ce69ef40fb80d94850fbf550e9c6a9e8fef02/labelbox/schema/project.py#L57

Is there a way to do this on the new schema?

**Comment by manuaero** [comment]
We have this in our roadmap
