### ISSUE TITLE
Support for IMAGE_OVERLAY metadata

### ISSUE THREAD

**Issue by tyler-c2s** [Labelbox/labelbox-python#99]
Hi, 

The DataRow class looks like it supports [IMAGE, TEXT, & VIDEO](https://github.com/Labelbox/labelbox-python/blob/c4fae6fe5d247eb17aee2be78ff6238aab8ee838/labelbox/schema/asset_metadata.py) metdata, but not the newer [IMAGE_OVERLAY metadata](https://labelbox.com/docs/assets-and-datasets/asset-information-overlay#type_image_overlay).

Would enable `datarow.create_metadata("IMAGE_OVERLAY", "https://labelbox.s3-us-west-2.amazonaws.com/coregistered-images/rgb.png")`

**Comment by manuaero** [comment]
Thanks! We've added this to our roadmap

**Comment by manuaero** [comment]
This is now released in the latest version: https://github.com/Labelbox/labelbox-python/releases/tag/v2.5.1
